name: Auto Update Fancode Group

on:
  schedule:
    - cron: "*/5 * * * *"   
  workflow_dispatch:        

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Download Fancode playlist
        run: |
          curl -L "https://raw.githubusercontent.com/IPTVFlixBD/Fancode-BD/refs/heads/main/playlist.m3u" -o fancode.m3u

      - name: Remove old Fancode section (if exists)
        run: |
          awk '
          BEGIN {skip=0}
          /#EXTINF/ && /group-title="Fancode"/ {skip=1}
          skip && /^$/ {skip=0; next}
          !skip {print}
          ' Test.m3u > tmp && mv tmp Test.m3u

      - name: Append updated Fancode group at the end
        run: |
          echo "" >> Test.m3u
          echo "# ----------- Fancode Auto Updated Group -----------" >> Test.m3u
          sed 's/^#EXTINF:-1/#EXTINF:-1 group-title="Fancode"/' fancode.m3u >> Test.m3u
          echo "" >> Test.m3u

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Test.m3u
          git commit -m "Auto-update Fancode group" || echo "No changes to commit"
          git push
