name: Auto Playlist Aggregator

on:
  schedule:
    - cron: "*/5 * * * *"  # প্রতি ৫ মিনিটে চলবে
  workflow_dispatch:        # চাইলে ম্যানুয়ালি চালানো যাবে

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write       # গিটহাবে push করার অনুমতি দেবে

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # --- ১. playlist.m3u ফাইলটি পরিষ্কার করা ---
      - name: Initialize or clean playlist.m3u
        run: |
          # নিশ্চিত করুন যে playlist.m3u ফাইলে শুধুমাত্র একটি #EXTM3U আছে
          echo "#EXTM3U" > playlist.m3u

      # --- ২. লোকাল ফাইল যুক্ত করা (আপনার রেপোজিটরিতে থাকা ফাইল) ---

      - name: Append Local Bangla Group
        run: |
          FILE_NAME="Bangla" # ফাইলের নাম bangla.m3u থেকে bangla করা হয়েছে
          if [ -f "$FILE_NAME" ]; then
            echo "" >> playlist.m3u
            echo "# ----------- Local Bangla Group -----------" >> playlist.m3u
            # #EXTM3U হেডার বাদ দিয়ে group-title যোগ করে Master ফাইলে যুক্ত করা হচ্ছে
            # এটি নিশ্চিত করে যে প্রতিটি চ্যানেলের জন্য group-title="Bangla" সেট হবে।
            grep -v '^#EXTM3U' "$FILE_NAME" | sed 's/^#EXTINF:-1/#EXTINF:-1 group-title="Bangla"/' >> playlist.m3u
            echo "" >> playlist.m3u
            echo "Local file $FILE_NAME successfully appended."
          else
            echo "Warning: Local file $FILE_NAME not found. Skipping."
          fi

      - name: Append Local Hindi Group
        run: |
          FILE_NAME="Hindi"
          if [ -f "$FILE_NAME" ]; then
            echo "" >> playlist.m3u
            echo "# ----------- Local Hindi Group -----------" >> playlist.m3u
            # #EXTM3U হেডার বাদ দিয়ে group-title যোগ করে Master ফাইলে যুক্ত করা হচ্ছে
            # এটি নিশ্চিত করে যে প্রতিটি চ্যানেলের জন্য group-title="Hindi" সেট হবে।
            grep -v '^#EXTM3U' "$FILE_NAME" | sed 's/^#EXTINF:-1/#EXTINF:-1 group-title="Hindi"/' >> playlist.m3u
            echo "" >> playlist.m3u
            echo "Local file $FILE_NAME successfully appended."
          else
            echo "Warning: Local file $FILE_NAME not found. Skipping."
          fi
          
      # (যদি অন্য কোনো লোকাল ফাইল থাকে, তবে এই block গুলো পুনরাবৃত্তি করুন)

      # --- ৩. এক্সটার্নাল GitHub/অন্যান্য লিঙ্ক যুক্ত করা (অন্য রেপোজিটরির লিঙ্ক) ---
      
      # এক্সটার্নাল সোর্স ১: Fancode (আপনার পূর্বের কোড)
      - name: Download and Append Fancode Playlist
        run: |
          EXTERNAL_URL="https://raw.githubusercontent.com/IPTVFlixBD/Fancode-BD/main/playlist.m3u"
          GROUP_NAME="Fancode Auto Updated"
          TEMP_FILE="fancode_temp.m3u"

          curl -L "$EXTERNAL_URL" -o "$TEMP_FILE"
          
          echo "" >> playlist.m3u
          echo "# ----------- $GROUP_NAME -----------" >> playlist.m3u
          # #EXTM3U হেডার বাদ দিয়ে group-title যোগ করে Master ফাইলে যুক্ত করা
          grep -v '^#EXTM3U' "$TEMP_FILE" | sed 's/^#EXTINF:-1/#EXTINF:-1 group-title="Fancode"/' >> playlist.m3u
          echo "" >> playlist.m3u
          rm "$TEMP_FILE"

      # এক্সটার্নাল সোর্স ২: New External Group Example
      - name: Download and Append New External Group
        run: |
          EXTERNAL_URL="https://raw.githubusercontent.com/AnotherUser/AnotherRepo/main/another.m3u"
          GROUP_NAME="Another External Group"
          TEMP_FILE="external_temp.m3u"

          curl -L "$EXTERNAL_URL" -o "$TEMP_FILE"
          
          echo "" >> playlist.m3u
          echo "# ----------- $GROUP_NAME -----------" >> playlist.m3u
          # এখানে 'Another' group-title ব্যবহার করা হয়েছে
          grep -v '^#EXTM3U' "$TEMP_FILE" | sed 's/^#EXTINF:-1/#EXTINF:-1 group-title="Another"/' >> playlist.m3u
          echo "" >> playlist.m3u
          rm "$TEMP_FILE"

      # --- ৪. কমিট এবং Push করা ---
      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u
          git commit -m "Auto-update master playlist with local and external groups" || echo "No changes to commit"
          git push
