name: Auto Playlist Aggregator

on:
  schedule:
    - cron: "*/5 * * * *"  # প্রতি ৫ মিনিটে চলবে
  workflow_dispatch:        # চাইলে ম্যানুয়ালি চালানো যাবে

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write       # গিটহাবে push করার অনুমতি দেবে

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # --- ১. playlist.m3u ফাইলটি পরিষ্কার করা (শুরুতে #EXTM3U নিশ্চিত) ---
      - name: Initialize or clean playlist.m3u
        run: |
          # নিশ্চিত করুন যে playlist.m3u ফাইলে শুধুমাত্র একটি #EXTM3U আছে
          echo "#EXTM3U" > playlist.m3u

      # --- ২. লোকাল/এক্সটার্নাল ফাইল যুক্ত করা (আপনার নতুন তালিকা অনুযায়ী) ---
      
      # 1. Live Sports (Local File)
      - name: 1. Append Local Live Sports Group
        run: |
          FILE_NAME="live_sports"
          GROUP_TITLE="Live Sports"
          if [ -f "$FILE_NAME" ]; then
            echo "" >> playlist.m3u
            echo "# ----------- Local $GROUP_TITLE Group -----------" >> playlist.m3u
            # #EXTM3U হেডার বাদ দিয়ে group-title যোগ করে Master ফাইলে যুক্ত করা হচ্ছে
            grep -v '^#EXTM3U' "$FILE_NAME" | sed "s/^#EXTINF:-1/#EXTINF:-1 group-title=\"$GROUP_TITLE\"/" >> playlist.m3u
            echo "" >> playlist.m3u
            echo "Local file $FILE_NAME successfully appended."
          else
            echo "Warning: Local file $FILE_NAME not found. Skipping."
          fi

      # 2. External Link: Fancode (Group)
      - name: 2. Download and Append Fancode Playlist (External Link)
        run: |
          EXTERNAL_URL="https://raw.githubusercontent.com/IPTVFlixBD/Fancode-BD/main/playlist.m3u"
          GROUP_NAME="Fancode Auto Updated"
          TEMP_FILE="fancode_temp.m3u"

          curl -L "$EXTERNAL_URL" -o "$TEMP_FILE"
          
          echo "" >> playlist.m3u
          echo "# ----------- $GROUP_NAME -----------" >> playlist.m3u
          # #EXTM3U হেডার বাদ দিয়ে group-title যোগ করে Master ফাইলে যুক্ত করা
          grep -v '^#EXTM3U' "$TEMP_FILE" | sed 's/^#EXTINF:-1/#EXTINF:-1 group-title="Fancode"/' >> playlist.m3u
          echo "" >> playlist.m3u
          rm "$TEMP_FILE"

      # 3. Bangla (Local File)
      - name: 3. Append Local Bangla Group
        run: |
          FILE_NAME="bangla"
          GROUP_TITLE="Bangla"
          if [ -f "$FILE_NAME" ]; then
            echo "" >> playlist.m3u
            echo "# ----------- Local $GROUP_TITLE Group -----------" >> playlist.m3u
            # #EXTM3U হেডার বাদ দিয়ে group-title যোগ করে Master ফাইলে যুক্ত করা হচ্ছে
            grep -v '^#EXTM3U' "$FILE_NAME" | sed "s/^#EXTINF:-1/#EXTINF:-1 group-title=\"$GROUP_TITLE\"/" >> playlist.m3u
            echo "" >> playlist.m3u
            echo "Local file $FILE_NAME successfully appended."
          else
            echo "Warning: Local file $FILE_NAME not found. Skipping."
          fi

      # 4. Indian Bangla (Local File)
      - name: 4. Append Local Indian Bangla Group
        run: |
          FILE_NAME="indian_bangla"
          GROUP_TITLE="Indian Bangla"
          if [ -f "$FILE_NAME" ]; then
            echo "" >> playlist.m3u
            echo "# ----------- Local $GROUP_TITLE Group -----------" >> playlist.m3u
            # #EXTM3U হেডার বাদ দিয়ে group-title যোগ করে Master ফাইলে যুক্ত করা হচ্ছে
            grep -v '^#EXTM3U' "$FILE_NAME" | sed "s/^#EXTINF:-1/#EXTINF:-1 group-title=\"$GROUP_TITLE\"/" >> playlist.m3u
            echo "" >> playlist.m3u
            echo "Local file $FILE_NAME successfully appended."
          else
            echo "Warning: Local file $FILE_NAME not found. Skipping."
          fi

      # 5. Indian Hindi (Local File)
      - name: 5. Append Local Indian Hindi Group
        run: |
          FILE_NAME="indian_hindi"
          GROUP_TITLE="Indian Hindi"
          if [ -f "$FILE_NAME" ]; then
            echo "" >> playlist.m3u
            echo "# ----------- Local $GROUP_TITLE Group -----------" >> playlist.m3u
            # #EXTM3U হেডার বাদ দিয়ে group-title যোগ করে Master ফাইলে যুক্ত করা হচ্ছে
            grep -v '^#EXTM3U' "$FILE_NAME" | sed "s/^#EXTINF:-1/#EXTINF:-1 group-title=\"$GROUP_TITLE\"/" >> playlist.m3u
            echo "" >> playlist.m3u
            echo "Local file $FILE_NAME successfully appended."
          else
            echo "Warning: Local file $FILE_NAME not found. Skipping."
          fi
          
      # 6. Educational (Local File)
      - name: 6. Append Local Educational Group
        run: |
          FILE_NAME="educational"
          GROUP_TITLE="Educational"
          if [ -f "$FILE_NAME" ]; then
            echo "" >> playlist.m3u
            echo "# ----------- Local $GROUP_TITLE Group -----------" >> playlist.m3u
            # #EXTM3U হেডার বাদ দিয়ে group-title যোগ করে Master ফাইলে যুক্ত করা হচ্ছে
            grep -v '^#EXTM3U' "$FILE_NAME" | sed "s/^#EXTINF:-1/#EXTINF:-1 group-title=\"$GROUP_TITLE\"/" >> playlist.m3u
            echo "" >> playlist.m3u
            echo "Local file $FILE_NAME successfully appended."
          else
            echo "Warning: Local file $FILE_NAME not found. Skipping."
          fi

      # 7. Sports (General) (Local File)
      - name: 7. Append Local Sports Group (General)
        run: |
          FILE_NAME="sports"
          GROUP_TITLE="Sports"
          if [ -f "$FILE_NAME" ]; then
            echo "" >> playlist.m3u
            echo "# ----------- Local $GROUP_TITLE Group -----------" >> playlist.m3u
            # #EXTM3U হেডার বাদ দিয়ে group-title যোগ করে Master ফাইলে যুক্ত করা হচ্ছে
            grep -v '^#EXTM3U' "$FILE_NAME" | sed "s/^#EXTINF:-1/#EXTINF:-1 group-title=\"$GROUP_TITLE\"/" >> playlist.m3u
            echo "" >> playlist.m3u
            echo "Local file $FILE_NAME successfully appended."
          else
            echo "Warning: Local file $FILE_NAME not found. Skipping."
          fi

      # 8. Kids (Local File)
      - name: 8. Append Local Kids Group
        run: |
          FILE_NAME="kids"
          GROUP_TITLE="Kids"
          if [ -f "$FILE_NAME" ]; then
            echo "" >> playlist.m3u
            echo "# ----------- Local $GROUP_TITLE Group -----------" >> playlist.m3u
            # #EXTM3U হেডার বাদ দিয়ে group-title যোগ করে Master ফাইলে যুক্ত করা হচ্ছে
            grep -v '^#EXTM3U' "$FILE_NAME" | sed "s/^#EXTINF:-1/#EXTINF:-1 group-title=\"$GROUP_TITLE\"/" >> playlist.m3u
            echo "" >> playlist.m3u
            echo "Local file $FILE_NAME successfully appended."
          else
            echo "Warning: Local file $FILE_NAME not found. Skipping."
          fi

      # --- ৩. কমিট এবং Push করা ---
      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u
          git commit -m "Auto-update master playlist with local and external groups" || echo "No changes to commit"
          git push
