name: Auto Playlist Aggregator

on:
  schedule:
    - cron: "*/5 * * * *"  # প্রতি ৫ মিনিটে চলবে
  workflow_dispatch:        # চাইলে ম্যানুয়ালি চালানো যাবে

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write       # গিটহাবে push করার অনুমতি দেবে

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # --- অতিরিক্ত ধাপ: Line Endings ফিক্স করা (ত্রুটি কমাতে সাহায্য করে) ---
      - name: Install dos2unix
        run: sudo apt-get update && sudo apt-get install -y dos2unix
        
      - name: Normalize Local Files (Line Endings)
        run: |
          echo "Fixing line endings for all local source files..."
          for file in Live_Sports Bangladesh Indian_Bangla Indian_Hindi Educational Sports Kids; do
            if [ -f "$file" ]; then
              dos2unix "$file"
              echo "Normalized line endings for $file"
            else
              echo "File $file not found. Skipping normalization."
            fi
          done

      # --- ১. Test.m3u ফাইলটি পরিষ্কার করা (শুরুতে #EXTM3U নিশ্চিত) ---
      - name: Initialize or clean Test.m3u
        run: |
          # নিশ্চিত করুন যে Test.m3u ফাইলে শুধুমাত্র একটি #EXTM3U আছে
          echo "#EXTM3U" > Test.m3u

      # --- ২. লোকাল/এক্সটার্নাল ফাইল যুক্ত করা (আপনার নতুন তালিকা অনুযায়ী) ---
      
      # 1. Live Sports (Local File)
      - name: 1. Append Local Live Sports Group
        run: |
          FILE_NAME="Live Sports"
          GROUP_TITLE="Live Sports"
          if [ -f "$FILE_NAME" ]; then
            echo "" >> Test.m3u # এই লাইনটি কেবল একটি নিউলাইন যোগ করবে
            # বিভাজক লাইনটি সম্পূর্ণভাবে মুছে ফেলা হলো
            # Single-line AWK ব্যবহার করা হয়েছে, যা ত্রুটিমুক্ত
            awk -v title="$GROUP_TITLE" '!/^#EXTM3U/ { if ($0 ~ /^#EXTINF:-1/) { sub(/^#EXTINF:-1/, "#EXTINF:-1 group-title=\"" title "\""); } print $0 }' "$FILE_NAME" >> Test.m3u
            echo "" >> Test.m3u
            echo "Local file $FILE_NAME successfully appended."
          else
            echo "Warning: Local file $FILE_NAME not found. Skipping."
          fi

      # 2. External Link: Fancode (Group)
      - name: 2. Download and Append Fancode Playlist (External Link)
        run: |
          EXTERNAL_URL="https://raw.githubusercontent.com/IPTVFlixBD/Fancode-BD/main/playlist.m3u"
          GROUP_TITLE="Fancode"
          TEMP_FILE="fancode_temp.m3u"

          curl -L "$EXTERNAL_URL" -o "$TEMP_FILE"
          
          echo "" >> Test.m3u # এই লাইনটি কেবল একটি নিউলাইন যোগ করবে
          # বিভাজক লাইনটি সম্পূর্ণভাবে মুছে ফেলা হলো
          # Single-line AWK ব্যবহার করা হয়েছে, যা ত্রুটিমুক্ত
          awk -v title="$GROUP_TITLE" '!/^#EXTM3U/ { if ($0 ~ /^#EXTINF:-1/) { sub(/^#EXTINF:-1/, "#EXTINF:-1 group-title=\"" title "\""); } print $0 }' "$TEMP_FILE" >> Test.m3u
          echo "" >> Test.m3u
          rm "$TEMP_FILE"

      # 3. Bangladesh (Local File)
      - name: 3. Append Local Bangladesh Group
        run: |
          FILE_NAME="Bangladesh"
          GROUP_TITLE="Bangladesh"
          if [ -f "$FILE_NAME" ]; then
            echo "" >> Test.m3u # এই লাইনটি কেবল একটি নিউলাইন যোগ করবে
            # বিভাজক লাইনটি সম্পূর্ণভাবে মুছে ফেলা হলো
            awk -v title="$GROUP_TITLE" '!/^#EXTM3U/ { if ($0 ~ /^#EXTINF:-1/) { sub(/^#EXTINF:-1/, "#EXTINF:-1 group-title=\"" title "\""); } print $0 }' "$FILE_NAME" >> Test.m3u
            echo "" >> Test.m3u
            echo "Local file $FILE_NAME successfully appended."
          else
            echo "Warning: Local file $FILE_NAME not found. Skipping."
          fi

      # 4. Indian Bangla (Local File)
      - name: 4. Append Local Indian Bangla Group
        run: |
          FILE_NAME="Indian Bangla"
          GROUP_TITLE="Indian Bangla"
          if [ -f "$FILE_NAME" ]; then
            echo "" >> Test.m3u # এই লাইনটি কেবল একটি নিউলাইন যোগ করবে
            # বিভাজক লাইনটি সম্পূর্ণভাবে মুছে ফেলা হলো
            awk -v title="$GROUP_TITLE" '!/^#EXTM3U/ { if ($0 ~ /^#EXTINF:-1/) { sub(/^#EXTINF:-1/, "#EXTINF:-1 group-title=\"" title "\""); } print $0 }' "$FILE_NAME" >> Test.m3u
            echo "" >> Test.m3u
            echo "Local file $FILE_NAME successfully appended."
          else
            echo "Warning: Local file $FILE_NAME not found. Skipping."
          fi

      # 5. Indian Hindi (Local File)
      - name: 5. Append Local Indian Hindi Group
        run: |
          FILE_NAME="Indian Hindi"
          GROUP_TITLE="Indian Hindi"
          if [ -f "$FILE_NAME" ]; then
            echo "" >> Test.m3u # এই লাইনটি কেবল একটি নিউলাইন যোগ করবে
            # বিভাজক লাইনটি সম্পূর্ণভাবে মুছে ফেলা হলো
            awk -v title="$GROUP_TITLE" '!/^#EXTM3U/ { if ($0 ~ /^#EXTINF:-1/) { sub(/^#EXTINF:-1/, "#EXTINF:-1 group-title=\"" title "\""); } print $0 }' "$FILE_NAME" >> Test.m3u
            echo "" >> Test.m3u
            echo "Local file $FILE_NAME successfully appended."
          else
            echo "Warning: Local file $FILE_NAME not found. Skipping."
          fi
          
      # 6. Educational (Local File)
      - name: 6. Append Local Educational Group
        run: |
          FILE_NAME="Educational"
          GROUP_TITLE="Educational"
          if [ -f "$FILE_NAME" ]; then
            echo "" >> Test.m3u # এই লাইনটি কেবল একটি নিউলাইন যোগ করবে
            # বিভাজক লাইনটি সম্পূর্ণভাবে মুছে ফেলা হলো
            awk -v title="$GROUP_TITLE" '!/^#EXTM3U/ { if ($0 ~ /^#EXTINF:-1/) { sub(/^#EXTINF:-1/, "#EXTINF:-1 group-title=\"" title "\""); } print $0 }' "$FILE_NAME" >> Test.m3u
            echo "" >> Test.m3u
            echo "Local file $FILE_NAME successfully appended."
          else
            echo "Warning: Local file $FILE_NAME not found. Skipping."
          fi

      # 7. Sports (General) (Local File)
      - name: 7. Append Local Sports Group (General)
        run: |
          FILE_NAME="Sports"
          GROUP_TITLE="Sports"
          if [ -f "$FILE_NAME" ]; then
            echo "" >> Test.m3u # এই লাইনটি কেবল একটি নিউলাইন যোগ করবে
            # বিভাজক লাইনটি সম্পূর্ণভাবে মুছে ফেলা হলো
            awk -v title="$GROUP_TITLE" '!/^#EXTM3U/ { if ($0 ~ /^#EXTINF:-1/) { sub(/^#EXTINF:-1/, "#EXTINF:-1 group-title=\"" title "\""); } print $0 }' "$FILE_NAME" >> Test.m3u
            echo "" >> Test.m3u
            echo "Local file $FILE_NAME successfully appended."
          else
            echo "Warning: Local file $FILE_NAME not found. Skipping."
          fi

      # 8. Kids (Local File)
      - name: 8. Append Local Kids Group
        run: |
          FILE_NAME="Kids"
          GROUP_TITLE="Kids"
          if [ -f "$FILE_NAME" ]; then
            echo "" >> Test.m3u # এই লাইনটি কেবল একটি নিউলাইন যোগ করবে
            # বিভাজক লাইনটি সম্পূর্ণভাবে মুছে ফেলা হলো
            awk -v title="$GROUP_TITLE" '!/^#EXTM3U/ { if ($0 ~ /^#EXTINF:-1/) { sub(/^#EXTINF:-1/, "#EXTINF:-1 group-title=\"" title "\""); } print $0 }' "$FILE_NAME" >> Test.m3u
            echo "" >> Test.m3u
            echo "Local file $FILE_NAME successfully appended."
          else
            echo "Warning: Local file $FILE_NAME not found. Skipping."
          fi

      # --- ৩. কমিট এবং Push করা ---
      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Test.m3u
          git commit -m "Auto-update master playlist with local and external groups" || echo "No changes to commit"
          git push
